// src/lib/axios.ts
import axios, { type AxiosRequestConfig } from "axios";
import { toast } from "sonner";

export const api = axios.create({
  baseURL: "/api",
  withCredentials: true,
});

export const getSecurityHeaders = () => {
  // Fallback for randomUUID if crypto is not available (e.g. non-HTTPS/insecure context)
  const generateUUID = () => {
    if (typeof crypto !== "undefined" && crypto.randomUUID) {
      return crypto.randomUUID();
    }
    // Simple fallback generator
    return "xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g, (c) => {
      const r = (Math.random() * 16) | 0;
      const v = c === "x" ? r : (r & 0x3) | 0x8;
      return v.toString(16);
    });
  };

  return {
    "X-Timestamp": Date.now().toString(),
    "X-Request-ID": generateUUID(),
    // NOTE: X-Signature is automatically generated by the server-side proxy 
    // in src/app/api/[...path]/route.ts to protect the SIGN_SECRET.
  };
};

export const getCSRFToken = () => {
  if (typeof document === "undefined") return undefined;
  return document.cookie
    .split("; ")
    .find((row) => row.startsWith("csrf_token="))
    ?.split("=")[1];
};

export const secureRequest = async <T>(
  method: "get" | "post" | "put" | "delete" | "patch",
  url: string,
  data?: unknown,
  config: AxiosRequestConfig = {}
): Promise<T> => {
  const headers = {
    ...getSecurityHeaders(),
    ...(getCSRFToken() ? { "X-CSRF-Token": getCSRFToken() } : {}),
    ...(config.headers || {}),
  };

  const res =
    method === "get" || method === "delete"
      ? await api.request({
          method,
          url,
          headers,
          withCredentials: true,
          ...config,
          params: data,
        })
      : await api.request({
          method,
          url,
          data: data ?? {}, // Ensure body is at least empty object for non-GET
          headers,
          withCredentials: true,
          ...config,
        });

  return res.data;
};

let isRedirectingToLogin = false;

api.interceptors.response.use(
  (response) => response,
  (error) => {
    const status = error?.response?.status as number | undefined;
    const requestUrl = String(error?.config?.url ?? "");

    if (
      status === 401 &&
      typeof window !== "undefined" &&
      !isRedirectingToLogin &&
      window.location.pathname !== "/login" &&
      !requestUrl.includes("/v1/auth/login") &&
      !requestUrl.includes("/v1/auth/logout")
    ) {
      isRedirectingToLogin = true;
      window.location.replace("/login?forceLogin=1");
    }

    if (status === 403) {
      const message = error?.response?.data?.meta?.message || "";
      if (message.includes("Feature not available in your current plan")) {
        toast.error("Feature Locked", {
          description: "This feature is not available in your current plan. Please upgrade to unlock.",
          action: {
            label: "Upgrade",
            onClick: () => {
              if (typeof window !== "undefined") {
                window.location.href = "/tenant-settings/billing";
              }
            }
          }
        });
      }
    }

    return Promise.reject(error);
  }
);
