services:
  attendance-app:
    image: kucingemas/attendance-app:latest
    container_name: attendance-app
    restart: always
    env_file:
      - .env
    ports:
      - "${HOST_PORT:-9001}:3000"
    networks:
      - web-proxy
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  web-proxy:
    external: true
