services:
  attendance-app:
    image: kucingemas/attendance-app:latest
    container_name: attendance-app
    restart: always
    ports:
      - "9001:9001"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
      - API_URL=${API_URL}
      - INTERNAL_SECRET=${INTERNAL_SECRET}
      - SIGN_SECRET=${SIGN_SECRET}
      - APP_URL=${APP_URL}
    # Optional: Monitoring and Logs
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
